parameters:
  rust: stable
  allow_fail: false
  cross: false
  envs: {}
  setup: []
  test_ignored: false
  single_threaded: false
  raw_opts: ''



jobs:
- job: ${{ parameters.name }}
  ${{ if eq(parameters.test_ignored, 'true') }}:
    displayName: cargo +${{ parameters.rust }} test -- --ignored
  ${{ if ne(parameters.test_ignored, 'true') }}:
    displayName: cargo +${{ parameters.rust }} test
  continueOnError: ${{ parameters.allow_fail }}
  ${{ if eq(parameters.cross, 'true') }}:
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04
        MacOS:
          vmImage: macOS-10.14
        Windows:
          vmImage: windows-2019
  ${{ if ne(parameters.cross, 'true') }}:
    variables:
      vmImage: ubuntu-16.04
  pool:
    vmImage: $(vmImage)
  variables:
    options: ''
  steps:
  - template: _setup.yml
    parameters:
      rust: ${{ parameters.rust }}
      setup: ${{ parameters.setup }}
  - ${{ if or(eq(parameters.single_threaded, 'true'), eq(parameters.test_ignored, 'true'))}}:
    - script: echo '##vso[task.setvariable variable=options]$(options) --'
  - ${{ if eq(parameters.single_threaded, 'true') }}:
    - script: echo '##vso[task.setvariable variable=options]$(options) --test_threads=1'
  - ${{ if eq(parameters.test_ignored, 'true')}}:
    - script: echo '##vso[task.setvariable variable=options]$(options) --ignored'
  - ${{ if eq(parameters.raw_opts, 'true') }}:
    - script: cargo test ${{ parameters.raw_opts }}
      displayName: Run tests (with... ${{ parameters.raw_opts }})
      env:
        ${{ insert }}: ${{ parameters.envs }}
  - ${{ if ne(parameters.raw_opts, 'true') }}:
    - script: cargo test $(options)
      displayName: Run tests
      env:
        ${{ insert }}: ${{ parameters.envs }}

