parameters:
  rust: stable
  allow_fail: false
  cross: false
  envs: {}
  setup: []
  test_ignored: false
  single_threaded: false
  features: '' # empty feature list is == default
  raw_opts: ''

jobs:
- job: ${{ parameters.name }}
  ${{ if eq('true', parameters.test_ignored) }}:
    displayName: cargo +${{ parameters.rust }} test -- --ignored
  ${{ if ne('true', parameters.test_ignored) }}:
    displayName: cargo +${{ parameters.rust }} test
  continueOnError: ${{ parameters.allow_fail }}
  ${{ if eq('true', parameters.cross) }}:
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04
        MacOS:
          vmImage: macOS-10.14
        Windows:
          vmImage: windows-2019
  variables:
    ${{ if ne('true', parameters.cross) }}:
      vmImage: ubuntu-16.04
    options: ''
  pool:
    vmImage: $(vmImage)
  steps:
  - template: _setup.yml
    parameters:
      rust: ${{ parameters.rust }}
      setup: ${{ parameters.setup }}
  # Cargo options go here
  - bash: echo '##vso[task.setvariable variable=options]$(options) --all'
  - ${{ if eq(true, parameters.features)}}:
    - bash: echo '##vso[task.setvariable variable=options]$(options) --features "${{ parameters.features }}"'
  # Add any raw args
  - ${{ if eq(true, parameters.raw_opts) }}:
    - bash: echo '##vso[task.setvariable variable=options]$(options) ${{ parameters.raw_opts }}'
  # Add any additional conditional libtest options to this check
  # Attempts to ensure that any raw args passed do not interfere
  - ${{ if and(or(eq(true, parameters.single_threaded), eq(true, parameters.test_ignored)), not(endsWith(parameters.raw_opts, '--'))) }}:
    - bash: echo '##vso[task.setvariable variable=options]$(options) --'
  # Options passed to libtest go here
  - ${{ if eq(true, parameters.single_threaded) }}:
    - bash: echo '##vso[task.setvariable variable=options]$(options) --test-threads=1'
  # Run tests with the given options
  - bash: cargo test $(options)
    displayName: Run tests
    env:
      ${{ insert }}: ${{ parameters.envs }}
  - ${{ if eq(true, parameters.test_ignored)}}:
    - bash: cargo test $(options) --ignored
      displayName: Run ignored tests
      env:
        ${{ insert }}: ${{ parameters.envs }}

